### ISSUE TITLE
Upgrading lldb-eval OSS-Fuzz to Ubuntu 20.04

### ISSUE THREAD

**Issue by DavidKorczynski** [google/lldb-eval#172]
Hi,

Recently OSS-Fuzz upgrade it's base builder images to Ubuntu 20.04 from the old 16.04 Xenial image. There has been a migration of projects all switching to Ubuntu 20.04 and lldb-eval is one of two remaining project to upgrade. I was looking to do this myself, but then I noticed in the OSS-Fuzz build you rely on LLVM releases published on the lldb-eval repository which is probably easiest for you to update. OSS-Fuzz now uses clang-14 (up from clang-12). 

Please see this issue on the OSS-Fuzz side of things: https://github.com/google/oss-fuzz/issues/6302

The specific lines that need change in lldb-eval are the following: 

https://github.com/google/oss-fuzz/blob/1c5c258a49303068b81d7813d53a88aa31b626e7/projects/lldb-eval/Dockerfile#L17-L21

If you change those lines in the build will break and will need upgrading, and that's essentially what I ask in this issue. It would be great if we could get it updated!

**Comment by werat** [comment]
Thanks for bringing this to our attention, we're looking into it.
